services:
  # DATABASES
  postgres-airflow:
    image: postgres:16-alpine
    container_name: airflow_db
    environment:
      - POSTGRES_USER=${AIRFLOW_DB_USER}
      - POSTGRES_PASSWORD=${AIRFLOW_DB_PASSWORD}
      - POSTGRES_DB=${AIRFLOW_DB_NAME}
    volumes:
      - ./data/airflow-db-data:/var/lib/postgresql/data:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AIRFLOW_DB_USER} -d ${AIRFLOW_DB_NAME}"]
      interval: 10s
      retries: 5

  postgres-dwh:
    image: postgres:17-alpine 
    container_name: lumia_dwh
    environment:
      - POSTGRES_USER=${DWH_DB_USER}
      - POSTGRES_PASSWORD=${DWH_DB_PASSWORD}
      - POSTGRES_DB=${DWH_DB_NAME}
    volumes:
      - ./data/dwh-data:/var/lib/postgresql/data:Z
      - ./dwh-init-scripts:/docker-entrypoint-initdb.d:Z
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DWH_DB_USER} -d ${DWH_DB_NAME}"]
      interval: 10s
      retries: 5

  # AIRFLOW
  airflow-common: &airflow-common
    build: 
      context: ./airflow-service 
    image: lumia-airflow:latest
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@postgres-airflow/${AIRFLOW_DB_NAME}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__CORE__TEST_CONNECTION=Enabled
      - X_API_KEY=${X_API_KEY}
    volumes:
      - ./airflow-service/dags:/opt/airflow/dags:Z
      - ./airflow-service/queries:/opt/airflow/queries:Z
      - ./airflow-service/raw_data:/opt/airflow/raw_data:Z
      - ./logs:/opt/airflow/logs:Z
      - /home/ksiki/.ssh/id_rsa:/home/airflow/.ssh/id_rsa:ro,Z
    depends_on:
      postgres-airflow:
        condition: service_healthy

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      postgres-airflow:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: scheduler
    depends_on:
      postgres-airflow:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init
        airflow users create \
          --username "${AIRFLOW_ADMIN_USER}" \
          --firstname Kolya \
          --lastname Admin \
          --role Admin \
          --email "${AIRFLOW_ADMIN_EMAIL}" \
          --password "${AIRFLOW_ADMIN_PASSWORD}" || true
          
  # API SERVICE 
  fastapi-app:
    build: 
      context: ./api-service 
    container_name: lumia_api
    depends_on:
      postgres-dwh:
        condition: service_healthy
    environment:
      - DB_URL=${DB_URL}
      - X_API_KEY=${X_API_KEY}
      - DEBUG=${DEBUG}
      - PYTHONPATH=/app
    volumes:
      - ./api-service/src:/app/src:z
    ports:
      - "8000:8000"
    command: python -m uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  airflow_db_data:
  dwh_data: